version: '3.8'

services:
  mysql:
    image: mariadb
    container_name: fb-crawler-mysql
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - ./data/mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fb-crawler-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8080:80"

  redis:
    image: bitnami/redis:7.0
    container_name: fb-crawler-redis
    volumes:
      - ./data/redis:/bitnami/redis/data
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
