version: '3.8'

services:
  redis:
    image: bitnami/redis:7.0
    container_name: fb-crawler-redis
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    networks:
      - fb-crawler-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fb-crawler-app
    env_file:
      - .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
    networks:
      - fb-crawler-network

  chrome1:
    image: browserless/chrome
    container_name: fb-crawler-chrome1
    networks:
      - fb-crawler-network
    ports:
      - "3111:3000"
    environment:
      - CONNECTION_TIMEOUT=-1

  chrome2:
    image: browserless/chrome
    container_name: fb-crawler-chrome2
    networks:
      - fb-crawler-network
    ports:
      - "3222:3000"
    environment:
      - CONNECTION_TIMEOUT=-1

networks:
  fb-crawler-network:
    driver: bridge
