version: '3.8'

services:
  redis:
    image: bitnami/redis:7.0
    container_name: fb-crawler-redis
    environment:
      - 'REDIS_PASSWORD=${REDIS_PASSWORD}'
    networks:
      - fb-crawler-network

  id-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint: ["npm", "run", "start-id-worker"]

  detail-worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detail-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint: ["npm", "run", "start-detail-worker"]

  board:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    ports:
      - "3123:3123"
    entrypoint: ["npm", "run", "start-board"]

  chrome1:
    image: browserless/chrome
    container_name: fb-crawler-chrome1
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3111:3000

  chrome2:
    image: browserless/chrome
    container_name: fb-crawler-chrome2
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3222:3000

networks:
  fb-crawler-network:
    driver: bridge
