version: "3.8"
services:
  redis:
    restart: on-failure:5
    image: bitnami/redis:7.0
    container_name: fb-crawler-redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - fb-crawler-network
  id-worker:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: id-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-id-worker
  ads-id-worker:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ads-id-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-ads-id-worker
  like-page-worker:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: like-page-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-like-page-worker
  detail-worker:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detail-worker
    env_file:
      - .env
    environment:
      CHROME_WS_ENDPOINT_DETAIL: ${CHROME_WS_ENDPOINT_DETAIL}
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-detail-worker
  ads-detail-worker:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ads-detail-worker
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-ads-detail-worker
  detail-worker-2:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: detail-worker-2
    env_file:
      - .env
    environment:
      CHROME_WS_ENDPOINT_DETAIL: ${CHROME_WS_ENDPOINT_DETAIL_2}
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    entrypoint:
      - npm
      - run
      - start-detail-worker
  board:
    restart: on-failure:5
    build:
      context: .
      dockerfile: Dockerfile
    container_name: board
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - fb-crawler-network
    ports:
      - 3123:3123
    entrypoint:
      - npm
      - run
      - start-board
  chrome_id:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_id
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3111:3000
  chrome_detail:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_detail
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3222:3000
  chrome_detail_2:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_detail_2
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3333:3000
  chrome_ads_id:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_ads_id
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3334:3000
  chrome_ads_detail:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_ads_detail
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3335:3000
  chrome_page_like:
    restart: on-failure:5
    image: browserless/chrome
    container_name: fb-crawler-chrome_page_like
    networks:
      - fb-crawler-network
    environment:
      - CONNECTION_TIMEOUT=-1
    ports:
      - 3336:3000
networks:
  fb-crawler-network:
    driver: bridge
