openapi: 3.0.0
info:
  title: Queue Monitoring API
  version: 1.0.0
paths:
  /jobs:
    get:
      summary: Get all crawl jobs
      operationId: getCrawlJobs
      responses:
        '200':
          description: List of crawl jobs
          
    post:
      summary: Create a new crawl job
      operationId: addCrawlJob
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                interval: 5
      responses:
        '200':
          description: Job added successfully
        '500':
          description: An error occurred while adding the job

  /jobs/{id}:
    delete:
      summary: Remove a crawl job by ID
      operationId: removeCrawlJob
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: ID of the job to be removed
      responses:
        '200':
          description: Job removed successfully
        '500':
          description: An error occurred while removing the job

  /reload:
    post:
      summary: Reload the queue
      operationId: reloadQueue
      responses:
        '200':
          description: Queue reloaded successfully
        '500':
          description: An error occurred while reloading the queue
